export const CONFIG_VAR = {
  APP_PORT: 'APP_PORT',
  DB_URI: 'DB_URI',

  URL_BACKEND_SERVER: 'URL_BACKEND_SERVER',
  URL_FRONTEND_SERVER: 'URL_FRONTEND_SERVER',

  JWT_ACCESS_KEY: 'JWT_ACCESS_KEY',
  JWT_REFRESH_KEY: 'JWT_REFRESH_KEY',

  JWT_MAIL_SECRET_KEY: 'JWT_MAIL_SECRET_KEY',
  EMAIL_NAME: 'EMAIL_NAME',
  EMAIL_APP_PASSWORD: 'EMAIL_APP_PASSWORD',

  CLOUDINARY_NAME: 'CLOUDINARY_NAME',
  CLOUDINARY_KEY: 'CLOUDINARY_KEY',
  CLOUDINARY_SECRET: 'CLOUDINARY_SECRET',

  REGION_API: 'REGION_API',
  GHN_TOKEN: 'GHN_TOKEN',
  GHN_REGION_API: 'GHN_REGION_API',
  GHN_SERVICE_API: 'GHN_SERVICE_API',
  GHN_SHOP_ID: 'GHN_SHOP_ID',
};

export const DEFAULT_PORT = 3000;
