export const SAFE_CHARSET =
  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~';

export const NUMERIC_CHARSET = '0123456789';

export const ALPHABET_CHARSET = 'abcdefghijklmnopqrstuvwxyz';

export const ALPHABET_UPPER_CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export const ALPHANUMERIC_CHARSET = 'abcdefghijklmnopqrstuvwxyz0123456789';

export const ALPHANUMERIC_UPPER_CHARSET =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

export const ALPHANUMERIC_MIXED_CHARSET =
  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
